var twitter = "https://twitter.com/akaErni__";
var github = "https://github.com/Erni0k";

whoami = [
  "<br>",
  "The paradox of “Who am I?” is: we never know, but, we constantly find out.",
  "<br>"
];
social = [
  "<br>",
  'twitter        <a href="' + twitter + '" target="_blank">twitter/akaErni__' + '</a>',
  'github         <a href="' + github + '" target="_blank">github/Erni0k' + "</a>",
  'discord:       <a>Erni#0666</a>',
  "<br>"
];
help = [
  "<br>",
  '<span class="command">whoami</span>         Who are you?',
  '<span class="command">social</span>         Display my socials',
  '<span class="command">history</span>        View command history',
  '<span class="command">help</span>           You obviously already know what this does',
  '<span class="command">clear</span>          Clear terminal',
  '<span class="command">banner</span>         Display the header',
  '<span class="command">pokemon</span>        What Pokemon are you today?',
  '<span class="command">date</span>           Displays current date',
  '<br>',
   'Remember the cake_is_a_lie',
  "<br>",
];
cake_is_a_lie = [
  'This was a triumph.',
  'I\'m making a note here: HUGE SUCCESS.',
  'It\'s hard to overstate my satisfaction.',
  'Aperture Science',
  'We do what we must',
  'because we can.',
  'For the good of all of us.',
  'Except the ones who are dead.',
  'But there\'s no sense crying over every mistake.',
  'You just keep on trying till you run out of cake.',
  'And the Science gets done.',
  'And you make a neat gun.',
  'For the people who are still alive.',
  'I\'m not even angry.',
  'I\'m being so sincere right now.',
  'Even though you broke my heart.',
  'And killed me.',
  'And tore me to pieces.',
  'And threw every piece into a fire.',
  'As they burned it hurt because I was so happy for you!',
  'Now these points of data make a beautiful line.',
  'And we\'re out of beta.',
  'We\'re releasing on time.',
  'So I\'m GLaD. I got burned.',
  'Think of all the things we learned',
  'for the people who are still alive.',
  'Go ahead and leave me.',
  'I think I prefer to stay inside.',
  'Maybe you\'ll find someone else to help you.',
  'Maybe Black Mesa',
  'THAT WAS A JOKE.',
  'HAHA. FAT CHANCE.',
  'Anyway, this cake is great.',
  'It\'s so delicious and moist.',
  'Look at me still talking',
  'when there\'s Science to do.',
  'When I look out there, it makes me GLaD I\'m not you.',
  'I\'ve experiments to run.',
  'There is research to be done.',
  'On the people who are still alive.',
  'And believe me I am still alive.',
  'I\'m doing Science and I\'m still alive.',
  'I feel FANTASTIC and I\'m still alive.',
  'While you\'re dying I\'ll be still alive.',
  'And when you\'re dead I will be still alive.,',
  'STILL ALIVE',
  ''
];

banner = [
'           __________                                 ',
'         .\'----------`.                              ',
'         | .--------. |                             ',
'         | |########| |       __________              ',
'         | |########| |      /__________\\             ',
'.--------| `--------\' |------|    --=-- |-------------.\n',
'|        `----,-.-----\'      |o ======  |             | _____               _  ',
'|       ______|_|_______     |__________|             ||  ___|             (_) ',
'|      /  %%%%%%%%%%%%  \\                             || |__   _ __  _ __   _  ',
'|     /  %%%%%%%%%%%%%%  \\                            ||  __| | \'__|| \'_ \\ | | ',
'|     ^^^^^^^^^^^^^^^^^^^^                            || |___ | |   | | | || | ',
'+-----------------------------------------------------+\\____/ |_|   |_| |_||_|',
'^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ',
  '<span class="color2">Welcome to my Web Terminal</span>',
  "<span class=\"color2\">For a list of available commands, use </span> <span class=\"command\">'help'</span><span class=\"color2\">.</span>",
];